[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture arm64",
    "apt-get update && apt-get install --assume-yes libglib2.0-dev:arm64 libgtk-3-dev:arm64 libssl-dev:arm64 pkg-config"
]


[target.x86_64-unknown-linux-gnu]
pre-build = [
    "apt-get update && apt-get install -y --no-install-recommends pkg-config libssl-dev libgtk-3-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libfontconfig1-dev build-essential libglib2.0-dev libatk1.0-dev libpango1.0-dev libcairo2-dev libgdk-pixbuf2.0-dev libjpeg-dev libpng-dev libwebp-dev libgif-dev"
]

[target.x86_64-pc-windows-msvc]
# Windows 构建配置
xargo = false
build-std = false

[target.aarch64-pc-windows-msvc]
# Windows ARM64 构建配置
xargo = false
build-std = false

[target.x86_64-apple-darwin]
# macOS x86_64 构建配置
xargo = false
build-std = false

[target.aarch64-apple-darwin]
# macOS ARM64 构建配置
xargo = false
build-std = false

[build.env]
passthrough = [
    "RUST_BACKTRACE",
    "RUST_LOG",
    "CARGO_TERM_COLOR",
]

[build]
xargo = false
build-std = false